import hashlib
import json
import cv2
import numpy as np
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi import Query
from fastapi.responses import FileResponse
from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from ..config import settings
from ..db import get_db
from ..models import Analysis, Notification, TokenTransaction, User
from .accounts import current_user
from uuid import uuid4
from ..schemas import AnalysisResponse, ArtifactLinks, Region
from ..services.report import build_demo_report
from ..services.storage import create_analysis_dir, safe_artifact_path
from ..services.trained_inference import TrainedInferenceEngine

router = APIRouter(prefix="/analyses", tags=["analyses"])
engine = TrainedInferenceEngine(settings.model_checkpoint, settings.model_device)

ALLOWED_TYPES = {"image/jpeg", "image/png", "image/webp"}
WARNING = "Probability and localization are generated by the trained multimodal checkpoint. Results apply to the model's training domain and are not a legal determination."


@router.get("/dataset/masks/{source_id}")
def dataset_mask(source_id: str):
    path = Path(settings.model_checkpoint).resolve().parent.parent / "validation_data" / "Mask" / (str(source_id) + "_mask.png")
    if not path.exists():
        raise HTTPException(status_code=404, detail="Ground-truth mask not found")
    return FileResponse(path, media_type="image/png")


def artifact_links(analysis_id: str) -> ArtifactLinks:
    base = f"{settings.api_prefix}/analyses/{analysis_id}"
    return ArtifactLinks(
        original=f"{base}/artifacts/original.jpg",
        overlay=f"{base}/artifacts/overlay.jpg",
        mask=f"{base}/artifacts/mask.png",
        heatmap=f"{base}/artifacts/heatmap.png",
        probability_map=f"{base}/artifacts/probability_map.png",
        report=f"{base}/report",
    )


def to_response(row: Analysis) -> AnalysisResponse:
    regions_path = Path(row.artifact_dir) / "regions.json"
    regions_data = json.loads(regions_path.read_text()) if regions_path.exists() else []
    evidence_path = Path(row.artifact_dir) / "model_evidence.json"
    evidence = json.loads(evidence_path.read_text()) if evidence_path.exists() else {}
    return AnalysisResponse(
        id=row.id,
        filename=row.filename,
        image_hash=row.sha256,
        verdict=row.verdict,
        preliminary_score=row.preliminary_score,
        manipulated_area_pct=row.manipulated_area_pct,
        region_count=row.region_count,
        width=row.width,
        height=row.height,
        caption=row.caption,
        caption_provided=bool(row.caption.strip()),
        multimodal_status=("Image and caption were processed by the trained CLIP-fusion model" if row.caption.strip() else "Image processed by the trained model; no caption was supplied"),
        model_status=row.model_status,
        model_version=evidence.get("model_version", "best.pt"),
        consistency_score=evidence.get("consistency_score"),
        clip_similarity=evidence.get("clip_similarity"),
        warning=WARNING,
        regions=[Region(**r) for r in regions_data],
        artifacts=artifact_links(row.id),
        created_at=row.created_at,
    )


def can_access(row: Analysis, user: User) -> bool:
    """Analysis records belong to their user, except for administrators."""
    return user.role == "admin" or row.user_id == user.id


@router.post("", response_model=AnalysisResponse)
async def create_analysis(
    image: UploadFile = File(...),
    caption: str = Form(default=""),
    analysis_mode: str = Form(default="demo"),
    user: User = Depends(current_user),
    db: Session = Depends(get_db),
):
    if image.content_type not in ALLOWED_TYPES:
        raise HTTPException(status_code=415, detail="Only JPG, PNG and WEBP images are supported")

    data = await image.read()
    if not data:
        raise HTTPException(status_code=400, detail="Uploaded image is empty")
    if len(data) > settings.max_upload_mb * 1024 * 1024:
        raise HTTPException(status_code=413, detail=f"Maximum upload size is {settings.max_upload_mb} MB")
    if user.token_balance < settings.verification_token_cost:
        raise HTTPException(
            status_code=402,
            detail=f"Insufficient tokens: an analysis costs {settings.verification_token_cost} tokens",
        )

    analysis_id, analysis_dir = create_analysis_dir()
    try:
        result = engine.analyze(data, analysis_dir, caption.strip())
    except Exception as exc:
        raise HTTPException(status_code=400, detail=f"Could not decode/process image: {exc}") from exc

    sha256 = hashlib.sha256(data).hexdigest()
    (analysis_dir / "regions.json").write_text(json.dumps(result.regions, indent=2))
    (analysis_dir / "model_evidence.json").write_text(json.dumps({
        "model_version": Path(settings.model_checkpoint).name,
        "consistency_score": result.consistency_score,
        "clip_similarity": result.clip_similarity,
    }, indent=2))

    row = Analysis(
        id=analysis_id,
        filename=image.filename or "uploaded-image",
        sha256=sha256,
        caption=caption.strip(),
        analysis_mode=analysis_mode,
        verdict=result.verdict,
        preliminary_score=result.preliminary_score,
        manipulated_area_pct=result.manipulated_area_pct,
        region_count=len(result.regions),
        width=result.width,
        height=result.height,
        model_status=engine.model_status,
        artifact_dir=str(analysis_dir),
        user_id=user.id,
        created_at=datetime.utcnow(),
    )
    db.add(row)
    user.token_balance -= settings.verification_token_cost
    db.add(TokenTransaction(
        id=str(uuid4()), user_id=user.id, delta=-settings.verification_token_cost,
        kind="verification", note="Image authenticity analysis",
    ))
    db.add(Notification(
        id=str(uuid4()), user_id=user.id, title="Verification complete",
        body=f"{settings.verification_token_cost} tokens were used for your image analysis.",
    ))
    db.commit()
    db.refresh(row)

    build_demo_report(analysis_dir / "report.pdf", analysis=row, regions=result.regions)
    return to_response(row)


@router.get("", response_model=list[AnalysisResponse])
def list_analyses(query: str = "", verdict: str = "", user: User = Depends(current_user), db: Session = Depends(get_db)):
    statement = select(Analysis)
    if user.role != "admin":
        statement = statement.where(Analysis.user_id == user.id)
    if query.strip():
        needle = "%" + query.strip() + "%"
        statement = statement.where(or_(Analysis.filename.ilike(needle), Analysis.sha256.ilike(needle)))
    if verdict.strip():
        statement = statement.where(Analysis.verdict == verdict.strip())
    rows = db.scalars(statement.order_by(Analysis.created_at.desc()).limit(100)).all()
    return [to_response(row) for row in rows]


@router.get("/duplicates/{sha256}", response_model=list[AnalysisResponse])
def duplicate_analyses(sha256: str, user: User = Depends(current_user), db: Session = Depends(get_db)):
    if len(sha256) != 64:
        raise HTTPException(status_code=400, detail="SHA-256 must contain 64 hexadecimal characters")
    rows = db.scalars(select(Analysis).where(Analysis.sha256 == sha256).order_by(Analysis.created_at.desc())).all()
    return [to_response(row) for row in rows if can_access(row, user)]


@router.get("/{analysis_id}", response_model=AnalysisResponse)
def get_analysis(analysis_id: str, user: User = Depends(current_user), db: Session = Depends(get_db)):
    row = db.get(Analysis, analysis_id)
    if row is None or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    return to_response(row)


@router.get("/compare/{left_id}/{right_id}", response_model=list[AnalysisResponse])
def compare_analyses(left_id: str, right_id: str, user: User = Depends(current_user), db: Session = Depends(get_db)):
    """Feature 32: retrieve two persisted analyses for a side-by-side view."""
    left, right = db.get(Analysis, left_id), db.get(Analysis, right_id)
    if not left or not right or not can_access(left, user) or not can_access(right, user):
        raise HTTPException(status_code=404, detail="Both analysis IDs are required")
    return [to_response(left), to_response(right)]


@router.get("/{analysis_id}/regions/{region_index}/crop")
def region_crop(analysis_id: str, region_index: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    """Feature 33: return an enlarged crop for a detected connected region."""
    row = db.get(Analysis, analysis_id)
    if not row or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    regions = json.loads((Path(row.artifact_dir) / "regions.json").read_text())
    region = next((item for item in regions if item["index"] == region_index), None)
    if not region:
        raise HTTPException(status_code=404, detail="Region not found")
    image = cv2.imread(str(Path(row.artifact_dir) / "original.jpg"))
    h, w = image.shape[:2]
    pad = max(12, int(max(region["width"], region["height"]) * 0.2))
    x0, y0 = max(0, region["x"] - pad), max(0, region["y"] - pad)
    x1, y1 = min(w, region["x"] + region["width"] + pad), min(h, region["y"] + region["height"] + pad)
    crop = cv2.resize(image[y0:y1, x0:x1], None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
    output = Path(row.artifact_dir) / ("region_" + str(region_index) + ".jpg")
    cv2.imwrite(str(output), crop)
    return FileResponse(output, media_type="image/jpeg")


@router.get("/{analysis_id}/artifacts/{name}")
def get_artifact(analysis_id: str, name: str, user: User = Depends(current_user), db: Session = Depends(get_db)):
    row = db.get(Analysis, analysis_id)
    if row is None or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    try:
        path = safe_artifact_path(Path(row.artifact_dir), name)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    if not path.exists():
        raise HTTPException(status_code=404, detail="Artifact not found")
    media_type = "image/png" if path.suffix == ".png" else "image/jpeg"
    return FileResponse(path, media_type=media_type)


@router.get("/{analysis_id}/report")
def get_report(analysis_id: str, user: User = Depends(current_user), db: Session = Depends(get_db)):
    row = db.get(Analysis, analysis_id)
    if row is None or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    path = Path(row.artifact_dir) / "report.pdf"
    if not path.exists():
        raise HTTPException(status_code=404, detail="Report not found")
    return FileResponse(path, media_type="application/pdf", filename=f"forensight-{analysis_id}.pdf")


@router.post("/{analysis_id}/gradcam")
def create_gradcam(analysis_id: str, user: User = Depends(current_user), db: Session = Depends(get_db)):
    """Feature 39: generate a classifier Grad-CAM explanation on demand."""
    row = db.get(Analysis, analysis_id)
    if row is None or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    original = Path(row.artifact_dir) / "original.jpg"
    if not original.exists():
        raise HTTPException(status_code=404, detail="Original image artifact is unavailable")
    try:
        engine.gradcam(original.read_bytes(), Path(row.artifact_dir), row.caption)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Could not create Grad-CAM: {exc}") from exc
    return {"artifact": settings.api_prefix + "/analyses/" + row.id + "/artifacts/gradcam.jpg", "method": "Grad-CAM of manipulation classification logit"}


@router.get("/{analysis_id}/localization-preview")
def localization_preview(analysis_id: str, threshold: float = Query(0.55, ge=0.0, le=1.0), user: User = Depends(current_user), db: Session = Depends(get_db)):
    """Feature 28: re-threshold a saved neural probability map without new inference."""
    row = db.get(Analysis, analysis_id)
    if row is None or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    path = Path(row.artifact_dir) / "probability_map.npy"
    if not path.exists():
        raise HTTPException(status_code=404, detail="Raw probability map is unavailable for this older analysis")
    probability = np.load(path)
    binary = (probability >= threshold).astype(np.uint8)
    count, labels, stats, _ = cv2.connectedComponentsWithStats(binary, connectivity=8)
    regions = []
    for label in range(1, count):
        x, y, width, height, area = (int(value) for value in stats[label])
        if area >= max(20, int(binary.size * 0.0006)):
            regions.append({"x": x, "y": y, "width": width, "height": height, "area_pct": round(100 * area / binary.size, 3)})
    return {"threshold": threshold, "highlighted_area_pct": round(float(binary.mean() * 100), 3), "regions": regions}


@router.get("/{analysis_id}/ground-truth-comparison")
def ground_truth_comparison(analysis_id: str, source_id: str, threshold: float = Query(0.55, ge=0.0, le=1.0), user: User = Depends(current_user), db: Session = Depends(get_db)):
    """Features 29–30: compare a saved prediction with an AutoSplice ground-truth mask."""
    row = db.get(Analysis, analysis_id)
    if row is None or not can_access(row, user):
        raise HTTPException(status_code=404, detail="Analysis not found")
    prediction_path = Path(row.artifact_dir) / "probability_map.npy"
    mask_path = Path(settings.model_checkpoint).resolve().parent.parent / "validation_data" / "Mask" / (str(source_id) + "_mask.png")
    if not prediction_path.exists() or not mask_path.exists():
        raise HTTPException(status_code=404, detail="Prediction map or ground-truth mask is unavailable")
    prediction = (np.load(prediction_path) >= threshold).astype(np.uint8)
    truth = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
    truth = (cv2.resize(truth, (prediction.shape[1], prediction.shape[0]), interpolation=cv2.INTER_NEAREST) > 127).astype(np.uint8)
    intersection = int(np.logical_and(prediction, truth).sum())
    pred_sum, truth_sum = int(prediction.sum()), int(truth.sum())
    union = int(np.logical_or(prediction, truth).sum())
    return {"source_id": source_id, "threshold": threshold, "dice": round((2 * intersection) / max(pred_sum + truth_sum, 1), 6), "iou": round(intersection / max(union, 1), 6), "ground_truth_mask": settings.api_prefix + "/analyses/dataset/masks/" + str(source_id)}
